config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Specific Pages
  root 'recipes#index'

  resources :measurements
  resources :ingredients
  resources :techniques
  resources :recipes, param: :slug
  resources :recipe_steps do
    put :sort, on: :collection
    post :build, on: :member
  end
  resources :steps

  # Authentication via Divise routes
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'contact',
      to: 'pages#contact',
      as: :contact

  # Resources
  resources :ajax_modal

  # Custom Error Routes
  match '/404',
        to: 'errors#not_found',
        via: :all
  match '/500',
        to: 'errors#internal_server_error',
        via: :all
end

app/models/recipe_step.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: recipe_steps
#
#  id            :bigint           not null, primary key
#  recipe_id     :bigint
#  stepable_type :string
#  stepable_id   :bigint
#  position      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

# RecipeStep is the through table for relating polymorphic stepable items to
#   the recipe.
class RecipeStep < ApplicationRecord
  belongs_to :stepable, polymorphic: true
  belongs_to :recipe

  validate :stepable_is_not_parent_recipe

  before_create :set_position

  attr_accessor :new_uuid

  accepts_nested_attributes_for :stepable,
                                # reject_if: :all_blank,
                                allow_destroy: true

  default_scope -> { order(position: :asc) }

  def build_stepable(params)
    self.stepable = stepable_type.constantize.new(params)
  end

  private

  def set_position
    self.position = recipe.recipe_steps.count + 1
  end

  def stepable_is_not_parent_recipe
    errors.add(:stepable_id, 'Recipe can not be part of itself.') if stepable == recipe
  end
end

app/controllers/recipe_steps_controller.rb
# frozen_string_literal: true

class RecipeStepsController < ApplicationController
  before_action :set_recipe_step, only: [:show, :edit, :update, :destroy]

  # GET /recipe_steps
  # GET /recipe_steps.json
  def index
    @recipe_steps = RecipeStep.all
  end

  # GET /recipe_steps/1
  # GET /recipe_steps/1.json
  def show
  end

  # GET /recipe_steps/new
  def new
    @recipe_step = RecipeStep.new
  end

  # POST /recipe_steps/build/:id
  def build
    @recipe = Recipe.find(params[:id])
    @recipe_step = RecipeStep.new(recipe: @recipe, stepable: Step.new)
    build_step_ingredient
    @new_uuid = SecureRandom.uuid
  end

  # GET /recipe_steps/1/edit
  def edit
    if @recipe_step.stepable.is_a?(Step)
      build_step_ingredient
    end
  end

  # POST /recipe_steps
  # POST /recipe_steps.json
  def create
    @recipe_step = RecipeStep.new(recipe_step_params)
    @new_uuid = recipe_step_params[:new_uuid]

    respond_to do |format|
      if @recipe_step.save
        format.html { redirect_to @recipe_step, notice: 'Recipe step was successfully created.' }
        format.js   { render :show }
        format.json { render :show, status: :created, location: @recipe_step }
      else
        format.html { render :new }
        format.js   { render :new }
        format.json { render json: @recipe_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_steps/1
  # PATCH/PUT /recipe_steps/1.json
  def update
    respond_to do |format|
      if @recipe_step.update(recipe_step_params)
        format.html { redirect_to @recipe_step, notice: 'Recipe step was successfully updated.' }
        format.json { render :show }
        format.js { render :show, status: :ok, location: @recipe_step }
      else
        format.html { render :edit }
        format.js   { render :edit }
        format.json { render json: @recipe_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_steps/1
  # DELETE /recipe_steps/1.json
  def destroy
    @recipe_step.destroy
    respond_to do |format|
      format.html { redirect_to recipe_steps_url, notice: 'Recipe step was successfully destroyed.' }
      format.js   { render :delete }
      format.json { head :no_content }
    end
  end

  # PUT /recipe_steps/sort
  def sort
    params[:recipe_steps].each do |_k, v|
      RecipeStep.find(v[:id]).update_attribute(:position, v[:position])
    end

    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_step
      @recipe_step = RecipeStep.find(params[:id])
    end

    def build_step_ingredient
      unless @recipe_step.stepable.step_ingredients.any?
        @recipe_step.stepable.step_ingredients.build
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_step_params
      params.require(:recipe_step).permit(
        :id,
        :recipe_id,
        :stepable_id,
        :stepable_type,
        :position,
        :new_uuid,
        stepable_attributes: [
          :id,
          :title,
          :description,
          step_ingredients_attributes: [
            :id,
            :_destroy,
            :ingredient_id,
            :technique_id,
            measurements_attributes: [
              :id,
              :unit,
              :scalar,
              :purpose,
              :_destroy
            ],
            ingredient_attributes: [
              :id,
              :title,
              :description,
              :_destroy
            ],
            technique_attributes: [
              :id,
              :title,
              :description,
              :_destroy
            ]
          ]
        ]
      )
    end
end

app/helpers/recipe_steps_helper.rb
module RecipeStepsHelper
  # take a stepable relation to a recipe and render the correct html to edit
  #   the relationship on the recipes edit page
  def render_recipe_step_ajax_edit_field(stepable)
    model_name = stepable.model_name.human
    param_key  = stepable.model_name.param_key
    route_key  = stepable.model_name.route_key
    id         = stepable.id
    html_key   = "recipe_step_edit_#{param_key}_#{id}"
    btn_key    = html_key + '_btn'

    if stepable.is_a? Step
      html = content_tag(:div, render(stepable).html_safe, id: html_key) +
             link_to("Edit #{model_name}", edit_step_path(stepable), remote: true, id: btn_key)
    else
      html = link_to("View #{model_name}",
                     "/#{route_key}/#{id}/edit",
                     onclick: "return confirm('Are you sure you want to quit editing this recipe?')")
    end

    html.html_safe
  end

  # Render the stepable_type appropriate to the returned stepable object
  #   attached to the form_builder
  #
  # This method is used for rendering the appropriate form fields when creating
  #   a new step in recipes/edit. If a stepable object has a predefined type
  #   that means that a object is being passed back most likely with an error.
  #   we want to render that field with the error immedeatly visible. So this
  #   method takes the type of the stepable object and renders the appropriate
  #   form field for that object.
  def render_stepable_type(form_builder)
    case form_builder.object.stepable_type
    when 'Recipe'
      render 'recipe_steps/stepable_types/select_recipe', f: form_builder
    when 'Technique'
      render 'recipe_steps/stepable_types/select_technique', f: form_builder
    else
      render 'recipe_steps/stepable_types/build_step', f: form_builder
    end

    # render 'recipe_steps/stepable_types/select_step', f: form_builder
  end

  # This method takes a form_builder object and a type string and will render
  #   an approprite link to create that type's form. Recipe, Technique, and Step
  #   are available to be added to a recipe, if it's anything else (mainly nil)
  #   we are building a new step.
  def render_stepable_type_link(form_builder, type = nil)
    case type
    when 'Recipe'
      name    = 'Select Recipe'
      partial = 'recipe_steps/stepable_types/select_recipe'
    when 'Technique'
      name    = 'Select Technique'
      partial = 'recipe_steps/stepable_types/select_technique'
    when 'Step'
      name    = 'Select Step'
      partial = 'recipe_steps/stepable_types/select_step'
    else
      name    = 'Build Step'
      partial = 'recipe_steps/stepable_types/build_step'
    end

    build_stepable_type_link(name, partial, form_builder)
  end

  def build_stepable_type_link(name, partial, form_builder)
    html = CGI.escapeHTML(render(partial, f: form_builder).to_str).html_safe

    link_to(name,
            'javascript:void(0)',
            class: 'stepable-select',
            'data-type': html)
  end
end

app/views/recipe_steps/_edit.html.haml
%ul.order-recipe-steps
  - recipe.recipe_steps.each do |recipe_step|
    = render recipe_step

=link_to('Add Step', build_recipe_step_path(recipe.id), method: :post, remote: :true)

app/views/recipe_steps/_fields.html.haml
.recipe-step-fields
  = f.input :recipe_id, as: :hidden, input_html: { value: f.object.recipe.id }

  - if @new_uuid
    -# If this is a field for adding a new recipe_step, pass the unique UUID
    = f.input :new_uuid, as: :hidden, input_html: { value: @new_uuid }

  = render_stepable_type_link(f, 'Recipe')
  |
  = render_stepable_type_link(f, 'Technique')
  |
  = render_stepable_type_link(f, 'Step')
  |
  = render_stepable_type_link(f)

  .stepable-select-fields
    -# Renders the correct field if the form needs to be reloaded due to an
      error. This is a helper method located in recipe_steps_helper.rb
    = render_stepable_type(f)

app/views/recipe_steps/_form.html.haml
= simple_form_for @recipe_step, validate: true do |f|

  = render 'fields', f: f

  .actions
    = f.button :submit, 'Save', data: { disable_with: 'Saving...' }

app/views/recipe_steps/_inline_form.html.haml
= simple_form_for @recipe_step, validate: true, remote: true do |f|

  = render 'fields', f: f

  .actions
    = f.button :submit, 'Save', data: { disable_with: 'Saving...' }

app/views/recipe_steps/_recipe_step.html.haml
%li.recipe-step{'data-id' => recipe_step.id || @new_uuid}
  .handle

  - if recipe_step.persisted?
    - if recipe_step.stepable.class == Recipe
      -# = render 'sub_recipe', recipe: recipe_step.stepable
      .subtitle Recipe
      %h4= recipe_step.stepable.title

      %p= recipe_step.stepable.description
    - elsif recipe_step.stepable.class == Technique
      %h4= recipe_step.stepable.title

      %p= recipe_step.stepable.description

    - if recipe_step.stepable.present?
      .edit-stepable
        -# app/helpers/recipe_steps_helper.rb
        = render_recipe_step_ajax_edit_field(recipe_step.stepable)

        .remove-step-button
          = link_to 'Delete Step', recipe_step_path(recipe_step), method: :delete, remote: true, data: { confirm: "Are you sure?" }

  - else
    = render 'inline_form', recipe_step: recipe_step

app/views/recipe_steps/build.js.erb
plain:
$('.order-recipe-steps').append('<%= j render "recipe_steps/recipe_step", recipe_step: @recipe_step %>');
$('.new_recipe_step').enableClientSideValidations();

app/views/recipe_steps/delete.js.erb
plain:
$('#flash-wrapper').html('<%= j render "components/flash", flash: {success: "Successfully Removed Step"} %>');
Site.flash();
$('.recipe-step[data-id=<%= @recipe_step.id %>]').remove();

app/views/recipe_steps/edit.html.haml
%h1 Editing recipe_step

= render 'form'

= link_to 'Show', @recipe_step
\|
= link_to 'Back', recipe_steps_path

app/views/recipe_steps/index.html.haml
%h1 Listing recipe_steps

%table
  %thead
    %tr
      %th Recipe
      %th Stepable
      %th Position
      %th
      %th
      %th

  %tbody
    - @recipe_steps.each do |recipe_step|
      %tr
        %td= recipe_step.recipe
        %td= recipe_step.stepable
        %td= recipe_step.position
        %td= link_to 'Show', recipe_step
        %td= link_to 'Edit', edit_recipe_step_path(recipe_step)
        %td= link_to 'Destroy', recipe_step, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Recipe step', new_recipe_step_path

app/views/recipe_steps/new.html.haml
%h1 New recipe_step

= render 'form'

= link_to 'Back', recipe_steps_path

app/views/recipe_steps/new.js.erb
plain:
$('.recipe-step[data-id=<%= @new_uuid %>]').remove();
$('.order-recipe-steps').append('<%= j render "recipe_steps/recipe_step", recipe_step: @recipe_step %>');
Site.flash();

app/views/recipe_steps/show.html.haml
%p#notice= notice

%p
  %b Recipe:
  = @recipe_step.recipe
%p
  %b Stepable:
  = @recipe_step.stepable
%p
  %b Position:
  = @recipe_step.position

= link_to 'Edit', edit_recipe_step_path(@recipe_step)
\|
= link_to 'Back', recipe_steps_path

app/views/recipe_steps/show.js.erb
plain:
$('#flash-wrapper').html('<%= j render "components/flash", flash: {success: "Successfully Added Step"} %>');
Site.flash();
$('.recipe-step[data-id=<%= @new_uuid %>]').before('<%= j render "recipe_steps/recipe_step", recipe_step: @recipe_step %>');
$('.recipe-step[data-id=<%= @new_uuid %>]').remove();