config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Specific Pages
  root 'recipes#index'

  resources :measurements
  resources :ingredients
  resources :techniques
  resources :recipes, param: :slug
  resources :recipe_steps do
    put :sort, on: :collection
    post :build, on: :member
  end
  resources :steps

  # Authentication via Divise routes
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'contact',
      to: 'pages#contact',
      as: :contact

  # Resources
  resources :ajax_modal

  # Custom Error Routes
  match '/404',
        to: 'errors#not_found',
        via: :all
  match '/500',
        to: 'errors#internal_server_error',
        via: :all
end

app/models/technique.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: techniques
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# Techniques are included in Recipe's to help display ways of achieveing goals.
#   Examples:
#     Pan Searing Chicken
#     Sharpening Knives
class Technique < ApplicationRecord
  include Stepable

  validates_presence_of :title
end

app/controllers/techniques_controller.rb
# frozen_string_literal: true

class TechniquesController < ApplicationController
  before_action :set_technique, only: [:show, :edit, :update, :destroy]

  # GET /techniques
  # GET /techniques.json
  def index
    @techniques = Technique.all
  end

  # GET /techniques/1
  # GET /techniques/1.json
  def show
  end

  # GET /techniques/new
  def new
    @technique = Technique.new
  end

  # GET /techniques/1/edit
  def edit
  end

  # POST /techniques
  # POST /techniques.json
  def create
    @technique = Technique.new(technique_params)

    respond_to do |format|
      if @technique.save
        format.html { redirect_to @technique, notice: 'Technique was successfully created.' }
        format.json { render :show, status: :created, location: @technique }
      else
        format.html { render :new }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /techniques/1
  # PATCH/PUT /techniques/1.json
  def update
    respond_to do |format|
      if @technique.update(technique_params)
        format.html { redirect_to @technique, notice: 'Technique was successfully updated.' }
        format.json { render :show, status: :ok, location: @technique }
      else
        format.html { render :edit }
        format.json { render json: @technique.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /techniques/1
  # DELETE /techniques/1.json
  def destroy
    @technique.destroy
    respond_to do |format|
      format.html { redirect_to techniques_url, notice: 'Technique was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technique
      @technique = Technique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technique_params
      params.require(:technique).permit(:name, :title, :description)
    end
end

app/helpers/techniques_helper.rb
# frozen_string_literal: true

module TechniquesHelper
end

app/views/techniques/_fields.html.haml
.technique-fields.fields
  %h2 New Technique
  = f.input :title
  = f.input :description, as: :text

  = link_to_remove_association('Select Existing Technique', f,
                               class: 'button button-warn',
                               wrapper_class: 'technique-fields')

app/views/techniques/_form.html.haml
= simple_form_for @technique do |f|
  - if @technique.errors.any?
    #error_explanation
      %h2= "#{pluralize(@technique.errors.count, "error")} prohibited this technique from being saved:"
      %ul
        - @technique.errors.full_messages.each do |message|
          %li= message

  = render 'fields', f: f

  .actions
    = f.button :submit, 'Save', data: { disable_with: 'Saving...' }

app/views/techniques/_technique.html.haml
%h4= technique.title
%p= technique.description

app/views/techniques/edit.html.haml
%h1 Editing technique

= render 'form'

= link_to 'Show', @technique
\|
= link_to 'Back', techniques_path

app/views/techniques/index.html.haml
%h1 Listing techniques

.table-wrapper
  %table
    %thead
      %tr
        %th Name
        %th Title
        %th Description
        %th
        %th
        %th

    %tbody
      - @techniques.each do |technique|
        %tr
          %td= technique.title
          %td= technique.title
          %td= technique.description
          %td= link_to 'Show', technique
          %td= link_to 'Edit', edit_technique_path(technique)
          %td= link_to 'Destroy', technique, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Technique', new_technique_path

app/views/techniques/new.html.haml
%h1 New technique

= render 'form'

= link_to 'Back', techniques_path

app/views/techniques/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @technique.title
%p
  %b Title:
  = @technique.title
%p
  %b Description:
  = @technique.description

= link_to 'Edit', edit_technique_path(@technique)
\|
= link_to 'Back', techniques_path