config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Specific Pages
  root 'recipes#index'

  resources :measurements
  resources :ingredients
  resources :techniques
  resources :recipes, param: :slug
  resources :recipe_steps do
    put :sort, on: :collection
    post :build, on: :member
  end
  resources :steps

  # Authentication via Divise routes
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'contact',
      to: 'pages#contact',
      as: :contact

  # Resources
  resources :ajax_modal

  # Custom Error Routes
  match '/404',
        to: 'errors#not_found',
        via: :all
  match '/500',
        to: 'errors#internal_server_error',
        via: :all
end

app/models/ingredient.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: ingredients
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# Ingredient's are included in recipes through the recipe's steps.
class Ingredient < ApplicationRecord
  validates_presence_of :title

  has_many :step_ingredients, dependent: :destroy
  has_many :steps, through: :step_ingredients
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :description)
    end
end

app/helpers/ingredients_helper.rb
# frozen_string_literal: true

module IngredientsHelper
end

app/views/ingredients/_fields.html.haml
.ingredient-fields.fields
  %h2 New Ingredient

  = f.input :title
  = f.input :description, as: :text

  = link_to_remove_association('Select Existing Ingredient', f,
                               class: 'button button-warn',
                               wrapper_class: 'ingredient-fields')

app/views/ingredients/_form.html.haml
= simple_form_for @ingredient, validate: true do |f|
  - if @ingredient.errors.any?
    #error_explanation
      %h2= "#{pluralize(@ingredient.errors.count, "error")} prohibited this ingredient from being saved:"
      %ul
        - @ingredient.errors.full_messages.each do |message|
          %li= message

  = render 'fields', f: f

  .actions
    = f.button :submit, 'Save', data: { disable_with: 'Saving...' }

app/views/ingredients/_ingredient.html.haml
.ingredient

app/views/ingredients/edit.html.haml
%h1 Editing ingredient

= render 'form'

= link_to 'Show', @ingredient
\|
= link_to 'Back', ingredients_path

app/views/ingredients/index.html.haml
%h1 Listing ingredients

.table-wrapper
  %table
    %thead
      %tr
        %th Name
        %th Description
        %th
        %th
        %th

    %tbody
      - @ingredients.each do |ingredient|
        %tr
          %td= ingredient.title
          %td= ingredient.description
          %td= link_to 'Show', ingredient
          %td= link_to 'Edit', edit_ingredient_path(ingredient)
          %td= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Ingredient', new_ingredient_path

app/views/ingredients/new.html.haml
%h1 New ingredient

= render 'form'

= link_to 'Back', ingredients_path

app/views/ingredients/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @ingredient.title
%p
  %b Description:
  = @ingredient.description

= link_to 'Edit', edit_ingredient_path(@ingredient)
\|
= link_to 'Back', ingredients_path