config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Specific Pages
  root 'recipes#index'

  resources :measurements
  resources :ingredients
  resources :techniques
  resources :recipes, param: :slug
  resources :recipe_steps do
    put :sort, on: :collection
    post :build, on: :member
  end
  resources :steps

  # Authentication via Divise routes
  devise_for :users, controllers: { registrations: 'registrations' }

  get 'contact',
      to: 'pages#contact',
      as: :contact

  # Resources
  resources :ajax_modal

  # Custom Error Routes
  match '/404',
        to: 'errors#not_found',
        via: :all
  match '/500',
        to: 'errors#internal_server_error',
        via: :all
end

app/models/measurement.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: measurements
#
#  id                 :bigint           not null, primary key
#  step_ingredient_id :bigint
#  unit               :string
#  scalar             :decimal(, )
#  purpose            :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

# Measurement is a Unit and Sacalar that associates with a ingredient to display
#   how much of something is necessary.
class Measurement < ApplicationRecord
  belongs_to :step_ingredient

  validates :scalar, presence: true, numericality: true

  def to_unit
    Unit.new("#{scalar} #{unit}")
  end
end

app/controllers/measurements_controller.rb
# frozen_string_literal: true

class MeasurementsController < ApplicationController
  before_action :set_measurement, only: [:show, :edit, :update, :destroy]

  # GET /measurements
  # GET /measurements.json
  def index
    @measurements = Measurement.all
  end

  # GET /measurements/1
  # GET /measurements/1.json
  def show
  end

  # GET /measurements/new
  def new
    @measurement = Measurement.new
  end

  # GET /measurements/1/edit
  def edit
  end

  # POST /measurements
  # POST /measurements.json
  def create
    @measurement = Measurement.new(measurement_params)

    respond_to do |format|
      if @measurement.save
        format.html { redirect_to @measurement, notice: 'Measurement was successfully created.' }
        format.json { render :show, status: :created, location: @measurement }
      else
        format.html { render :new }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /measurements/1
  # PATCH/PUT /measurements/1.json
  def update
    respond_to do |format|
      if @measurement.update(measurement_params)
        format.html { redirect_to @measurement, notice: 'Measurement was successfully updated.' }
        format.json { render :show, status: :ok, location: @measurement }
      else
        format.html { render :edit }
        format.json { render json: @measurement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /measurements/1
  # DELETE /measurements/1.json
  def destroy
    @measurement.destroy
    respond_to do |format|
      format.html { redirect_to measurements_url, notice: 'Measurement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_measurement
      @measurement = Measurement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def measurement_params
      params.require(:measurement).permit(:step_ingredient_id, :unit, :scalar, :purpose)
    end
end

app/helpers/measurements_helper.rb
# frozen_string_literal: true

module MeasurementsHelper
end

app/views/measurements/_fields.html.haml
.measurement-fields.fields
  -# .combined-measurement-field.inline-fields
  = f.label :measurement,
            class: 'measurement-label'

  = f.input :scalar,
            label: false,
            wrapper_html: { class: 'measurement-scalar' }

  = f.input :unit,
            as: :select,
            collection: Unit.measurements.map { |k, v| [v, k] },
            label: false,
            wrapper_html: { class: 'measurement-unit' }

  = link_to_remove_association('&times;'.html_safe,
                               f,
                               class: 'button button-warn',
                               wrapper_class: 'measurement-fields')

app/views/measurements/_form.html.haml
= simple_form_for @measurement do |f|
  - if @measurement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@measurement.errors.count, "error")} prohibited this measurement from being saved:"
      %ul
        - @measurement.errors.full_messages.each do |message|
          %li= message

  = render 'fields', f: f

  .actions
    = f.button :submit, 'Save', data: { disable_with: 'Saving...' }

app/views/measurements/edit.html.haml
%h1 Editing measurement

= render 'form'

= link_to 'Show', @measurement
\|
= link_to 'Back', measurements_path

app/views/measurements/index.html.haml
%h1 Listing measurements

%table
  %thead
    %tr
      %th Step ingredient
      %th Unit
      %th Scalar
      %th Purpose
      %th
      %th
      %th

  %tbody
    - @measurements.each do |measurement|
      %tr
        %td= measurement.step_ingredient
        %td= measurement.unit
        %td= measurement.scalar
        %td= measurement.purpose
        %td= link_to 'Show', measurement
        %td= link_to 'Edit', edit_measurement_path(measurement)
        %td= link_to 'Destroy', measurement, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Measurement', new_measurement_path

app/views/measurements/new.html.haml
%h1 New measurement

= render 'form'

= link_to 'Back', measurements_path

app/views/measurements/show.html.haml
%p#notice= notice

%p
  %b Step ingredient:
  = @measurement.step_ingredient
%p
  %b Unit:
  = @measurement.unit
%p
  %b Scalar:
  = @measurement.scalar
%p
  %b Purpose:
  = @measurement.purpose

= link_to 'Edit', edit_measurement_path(@measurement)
\|
= link_to 'Back', measurements_path